SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
     FROM REST_INFO
     GROUP BY FOOD_TYPE) M
ON R.FAVORITES = M.MAX_FAV AND R.FOOD_TYPE = M.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC;