SELECT 
    ugu.USER_ID,
    ugu.NICKNAME,
    CONCAT(ugu.CITY, ' ', ugu.STREET_ADDRESS1, ' ', ugu.STREET_ADDRESS2) AS 전체주소,
    INSERT(INSERT(ugu.TLNO,4,0,'-'),9,0,'-') AS 전화번호
FROM USED_GOODS_USER ugu
WHERE ugu.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)
ORDER BY ugu.USER_ID DESC;