SELECT ai.ANIMAL_ID,ai.ANIMAL_TYPE,ai.NAME
FROM ANIMAL_OUTS ao
JOIN ANIMAL_INS ai ON ao.ANIMAL_ID = ai.ANIMAL_ID
WHERE ai.SEX_UPON_INTAKE LIKE("Intact%") AND 
      SUBSTRING_INDEX(ao.SEX_UPON_OUTCOME,' ',1) IN ('Spayed','Neutered')
ORDER BY ai.ANIMAL_ID;
