SELECT u.USER_ID,u.NICKNAME,SUM(PRICE) AS TOTAL_SALES 
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD ub ON u.USER_ID = ub.WRITER_ID
WHERE ub.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;